spring:
  application:
    name: interface-proxy-server

  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:proxydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  # secret yaml 파일 profile
  profiles:
    active: secret

# 서버 포트
server:
  port: 8080

# 인터페이스 정의 경로
interface:
  definition-path: classpath:interfaces/

# 로깅 레벨
logging:
  level:
    root: INFO
    com.taekwang.proxy: DEBUG
    com.sap.conn.jco: DEBUG